# Groupby

The groupby method allows you to group rows of data together and call aggregate functions

### Import `numpy` with the alias `np` and `pandas` with the alias `pd`

In [0]:
import numpy as np
import pandas as pd

### Load Data

<hr>

##### Mount Drive - **Google Colab Only Step**

When using google colab in order to access files on our google drive we need to mount the drive by running the below python cell, then clicking the link it generates and pasting the code in the cell.

In [27]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Change Directory To Access The Dependent Files - **Google Colab Only Step**

In [28]:
directory = "teacher"
if (directory == "student"):
  %cd drive/Colab\ Notebooks/intro-to-python/
else:
  %cd drive/Shared\ drives/Rubrik/Data\ Science\ Track/intro-to-python

[Errno 2] No such file or directory: 'drive/Shared drives/Rubrik/Data Science Track/intro-to-python'
/content/drive/Shared drives/Rubrik/Data Science Track/intro-to-python

#### `.read_csv()`: Load `csv` data into a `pandas` DataFrame called `ri`.

Directory system keys:

`./` - current directory 

`../` - previous directory; **Note** that the current folder lives inside the previous folder.

The data is in the `data` folder inside a folder called `data` which lives inside the current directory. The filename is `rhode-island-police-stops.csv`

```python
# Fix Me!
path_to_file = "path/to/rhode-island-police-stops.csv"

ri = pd.read_csv(path_to_file)
```

In [29]:
path_to_file = "./data/rhode-island-police-stops.csv"
 
ri = pd.read_csv(path_to_file)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (1,7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

<br>

### Explore Columns.
> Before we can group `rows`, we should have an idea of what `column` we want to `group` by and what summary statistic were interested in exploring.

```python
ri.dtypes
```

In [30]:
ri.dtypes

date_and_time          object
police_department      object
driver_gender          object
driver_age_raw        float64
driver_age            float64
driver_race            object
violation              object
search_conducted       object
search_type            object
contraband_found         bool
stop_outcome           object
is_arrested            object
stop_duration          object
out_of_state           object
drugs_related_stop       bool
district               object
dtype: object

We will pick to group by `driver_race`, so it is important that we know how many unique groups we will be working with.
<br>
Use the `.unique()` method on the `driver_race` column to see those groups!

```python 
ri['driver_race'].unique()
```

In [31]:
ri['driver_race'].unique()

array(['White', nan, 'Black', 'Hispanic', 'Asian', 'Other'], dtype=object)

<br>

### `.groupby()`

**Let's use the `.groupby()` method to group `rows` together based off of driver_race, in this case.** 
> Since we're grouping `rows` by `driver_race`. This will create a `DataFrameGroupBy` object that we can then call aggregate statistics on!

```python
ri.groupby('driver_race')
```

In [32]:
ri.groupby('driver_race')

**You can save this object as a new variable:**

```python
by_race = ri.groupby("driver_race")
print(by_race)
```

In [33]:
by_race = ri.groupby("driver_race")
print(by_race)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7f9fbb9512e8>

**And then call aggregate methods off the object:**

Now that the dataframe has been stored in a `groupby` object we can ask for summary statistics.

This `.mean()` on `by_race` is essentially asking for the `.mean()` of all numerical features in `df`, for each group in `driver_race`.
<br>
This allows us to answer questions like:
* What was the average `driver_age` for all `White` drivers
* What is the average rate of `contrabound_found` for each race
* etc...

```python
by_race.mean()
```

In [34]:
by_race.mean()

             driver_age_raw  driver_age  contraband_found  drugs_related_stop
driver_race
Asian           1971.609465   33.574076          0.007251            0.004522
Black           1971.010572   33.107083          0.023039            0.016959
Hispanic        1975.502071   31.509494          0.019896            0.014212
Other           1957.361607   34.761295          0.000744            0.000744
White           1969.684847   34.549688          0.011162            0.008087

<br>

#### All together now!

```python
ri.groupby('driver_race').mean()
```

In [35]:
ri.groupby('driver_race').mean()

             driver_age_raw  driver_age  contraband_found  drugs_related_stop
driver_race
Asian           1971.609465   33.574076          0.007251            0.004522
Black           1971.010572   33.107083          0.023039            0.016959
Hispanic        1975.502071   31.509494          0.019896            0.014212
Other           1957.361607   34.761295          0.000744            0.000744
White           1969.684847   34.549688          0.011162            0.008087

<hr>
<br>
<br>

**More examples of aggregate methods:**

`by_race` is holding the grouping of all rows in the dataframe, by race. So when we call the `aggregate` method `.std()` this will return the `standard deviation` of all of the numerical columns, grouped by race.

```python
by_race.std()
```

In [36]:
by_race.std()

             driver_age_raw  driver_age  contraband_found  drugs_related_stop
driver_race
Asian             99.328311   11.623732          0.084846            0.067097
Black            113.427006   11.486915          0.150029            0.129117
Hispanic          94.203860   10.535625          0.139646            0.118364
Other            186.234266   11.659297          0.027277            0.027277
White            108.713972   13.214862          0.105060            0.089566

<br>

`by_race` grouped all rows in the `ri` dataframe by race. So when we call the aggregate method `.min()` this will return the `minimum values` of all of the numerical columns, grouped by race. This allows us to know who the youngest person of each race was in the dataframe, shortest stop duration, etc...

```python
by_race.min()
```

In [37]:
by_race.min()

                   date_and_time  driver_age_raw  ...  drugs_related_stop district
driver_race                                       ...
Asian        2005-07-13 16:20:00             0.0  ...               False  Zone K1
Black        2005-01-06 01:30:00             0.0  ...               False  Zone K1
Hispanic     2005-01-18 17:13:00             0.0  ...               False  Zone K1
Other        2005-10-02 09:30:00             0.0  ...               False  Zone K1
White        2005-01-02 01:55:00             0.0  ...               False  Zone K1

[5 rows x 12 columns]

<br>

`by_race` grouped all rows in the `ri` dataframe by race. So when we call the aggregate method `.max()` this will return the `maximum values` of all of the numerical columns, grouped by race. This allows us to know who the oldest person of each race was in the dataframe, longest stop duration, etc...

```python
by_race.max()
```

In [38]:
by_race.max()

                   date_and_time  driver_age_raw  ...  drugs_related_stop district
driver_race                                       ...
Asian        2015-12-31 22:26:00          2006.0  ...                True  Zone X4
Black        2015-12-31 21:32:00          2010.0  ...                True  Zone X4
Hispanic     2015-12-31 23:48:00          2014.0  ...                True  Zone X4
Other        2015-12-27 13:18:00          2006.0  ...                True  Zone X4
White        2015-12-31 23:44:00          8801.0  ...                True  Zone X4

[5 rows x 12 columns]

<br>

`by_race` grouped all rows in the `ri` dataframe by race. So when we call the aggregate method `.describe()` this will return the `descriptive statistics` for all numerical columns in the dataframe, grouped by race. Note: `.describe()` incorporates things like `.mean()`, `.median()`, `.min()`, `.max()`, etc... into a single method call, Where each row in the resulting dataframe represents a race from the original dataframe.

```python
by_race.describe()
```

In [39]:
by_race.describe()

            driver_age_raw                           ... driver_age
                     count         mean         std  ...        50%   75%   max
driver_race                                          ...
Asian              12826.0  1971.609465   99.328311  ...       31.0  41.0  87.0
Black              68579.0  1971.010572  113.427006  ...       30.0  40.0  93.0
Hispanic           53124.0  1975.502071   94.203860  ...       29.0  38.0  95.0
Other               1344.0  1957.361607  186.234266  ...       32.0  42.0  88.0
White             344734.0  1969.684847  108.713972  ...       31.0  44.0  99.0

[5 rows x 16 columns]

<br>

#### We can also get descriptive statistics on categorical columns

Do this by invoking the `describe` method and passing the the following argument:
```python 
by_race.describe(include=object)
```

In [40]:
by_race.describe(include=object)

            date_and_time                               ... district
                    count  unique                  top  ...   unique      top   freq
driver_race                                             ...
Asian               12826   12571  2008-03-19 00:00:00  ...        6  Zone K3   4204
Black               68579   65609  2014-02-22 23:54:00  ...        6  Zone X4  23124
Hispanic            53125   51132  2012-02-19 10:02:00  ...        6  Zone X4  19355
Other                1344    1315  2006-07-04 09:40:00  ...        6  Zone K3    451
White              344734  310256  2015-01-10 09:11:00  ...        6  Zone X4  79885

[5 rows x 44 columns]

Calling `.transpose()` on a `.describe()` dataframe switches the `row` and `column` `indices`, so instead of each `row` being a race, each `column` is now the race. 
<br>
This is particularly useful when you have a `large number of columns` and a `small number of rows`, that way when you transpose it makes the columns easier to read.

```python
by_race.describe().transpose()
```

In [41]:
by_race.describe().transpose()

driver_race                  Asian         Black  ...        Other          White
driver_age_raw count  12826.000000  68579.000000  ...  1344.000000  344734.000000
               mean    1971.609465   1971.010572  ...  1957.361607    1969.684847
               std       99.328311    113.427006  ...   186.234266     108.713972
               min        0.000000      0.000000  ...     0.000000       0.000000
               25%     1969.000000   1970.000000  ...  1966.750000    1966.000000
               50%     1979.000000   1980.000000  ...  1977.000000    1979.000000
               75%     1986.000000   1987.000000  ...  1984.000000    1986.000000
               max     2006.000000   2010.000000  ...  2006.000000    8801.000000
driver_age     count  12791.000000  68321.000000  ...  1328.000000  343546.000000
               mean      33.574076     33.107083  ...    34.761295      34.549688
               std       11.623732     11.486915  ...    11.659297      13.214862
               min       16.000000     15.000000  ...    17.000000      15.000000
               25%       24.000000     24.000000  ...    26.000000      23.000000
               50%       31.000000     30.000000  ...    32.000000      31.000000
               75%       41.000000     40.000000  ...    42.000000      44.000000
               max       87.000000     93.000000  ...    88.000000      99.000000

[16 rows x 5 columns]

<br>

Since we `transposed` the descriptive statistics dataframe, grouped by race. We can now grab the descriptive statistics for a single race with the following code, Note that it was the `.transpose()` that made the column indexing of `['Asian']` possible.

```python
by_race.describe().transpose()['Asian']
```

In [42]:
by_race.describe().transpose()['Asian']

driver_age_raw  count    12826.000000
                mean      1971.609465
                std         99.328311
                min          0.000000
                25%       1969.000000
                50%       1979.000000
                75%       1986.000000
                max       2006.000000
driver_age      count    12791.000000
                mean        33.574076
                std         11.623732
                min         16.000000
                25%         24.000000
                50%         31.000000
                75%         41.000000
                max         87.000000
Name: Asian, dtype: float64

#### If we didn't transpose the returned data frame we would need to use the `loc` bracket notation to target the desired race's numerical summary statistics.

```python 
by_race.describe().loc['Other']
```

In [43]:
by_race.describe().loc['Other']

driver_age_raw  count    1344.000000
                mean     1957.361607
                std       186.234266
                min         0.000000
                25%      1966.750000
                50%      1977.000000
                75%      1984.000000
                max      2006.000000
driver_age      count    1328.000000
                mean       34.761295
                std        11.659297
                min        17.000000
                25%        26.000000
                50%        32.000000
                75%        42.000000
                max        88.000000
Name: Other, dtype: float64

### We can also invoke a select group of DataFrame methods of our choice using the `agg` method and passing in a list as an argument of the desired methods we want invoked on the DataFrame  

Remember that `pandas` is built on top of `numpy`, so once we have used pandas' group by method that returns a dataframe we can use numpy's prebuilt methods to understand our dataset better.

[List of numpy calculation methods to consider](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#calculation)

```python
by_race.agg([np.mean, np.max, ...]) # Do not invoke the methods
```

In [48]:
by_race.agg([np.mean, np.max ]) # Do not invoke the methods

            driver_age_raw         driver_age  ... contraband_found drugs_related_stop
                      mean    amax       mean  ...             amax               mean  amax
driver_race                                    ...
Asian          1971.609465  2006.0  33.574076  ...             True           0.004522  True
Black          1971.010572  2010.0  33.107083  ...             True           0.016959  True
Hispanic       1975.502071  2014.0  31.509494  ...             True           0.014212  True
Other          1957.361607  2006.0  34.761295  ...             True           0.000744  True
White          1969.684847  8801.0  34.549688  ...             True           0.008087  True

[5 rows x 8 columns]