# SF Salaries Exercise 

Welcome to a quick exercise for you to practice your pandas skills! We will be using the [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) from Kaggle! Yes, **Real-World** Data this time!
<br>
Just follow along and complete the tasks outlined in bold below. The tasks will get harder and harder as you go along.

**1. Import numpy as `np` and pandas as `pd`**

In [0]:
import numpy as np 
import pandas as pd

<br>

**2. Load Data**

<hr>

##### Mount Drive - **Google Colab Only Step**

When using google colab in order to access files on our google drive we need to mount the drive by running the below python cell, then clicking the link it generates and pasting the code in the cell.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

Change Directory To Access The Dependent Files - **Google Colab Only Step**

In [3]:
directory = "teacher"
if (directory == "student"):
  %cd drive/Colab\ Notebooks/intro-to-python/
else:
  %cd drive/Shared\ drives/Rubrik/Data\ Science\ Track/intro-to-python

/content/drive/Shared drives/Rubrik/Data Science Track/intro-to-python

**Read in the San Francisco csv file and set it to a dataframe called `sal`**

The file name is `sf-salaries.csv` which is located in the `data` directory which lives inside the current directory.

In [0]:
sal = pd.read_csv('./data/sf-salaries.csv')

<br>

**3. Check the `head` of the DataFrame.**

In [6]:
sal.head()

   Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

<br>

**4. How many `rows` and `columns` are there?**

In [7]:
sal.shape

(148654, 13)

<br>

#### 5. What does each `row` represent? A purchase, A company, ...??

In [0]:
An employees salary

<br>

**6. What is the `dtype` of the `JobTitle` column?**

In [10]:
sal.dtypes['JobTitle']

dtype('O')

<br>

**7. How many `unique` `agencies` in `Agency` column?**
Does this make sense...?

In [11]:
sal['Agency'].nunique()

1

Yes because it is a San Francisco based dataset

<br>

**8. use the `.isinull().sum()` method to find the total number of `Nan` in `BasePay`.**

In [12]:
sal['BasePay'].isnull().sum()

609

<br>

**9. What is the average `BasePay`?**

In [13]:
sal['BasePay'].mean()

66325.44884050643

<br>

**10. What is the highest amount of `OvertimePay` in the dataset?**

In [15]:
sal['OvertimePay'].max()

245131.88

<br>

**11. What is the `JobTitle` of  `JOSEPH DRISCOLL`?**
> **Note:** Use all caps, otherwise you may get an answer that doesn't match up —there is a lowercase `Joseph Driscoll`).

In [24]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']["JobTitle"]

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

<br>

**12. How much does `JOSEPH DRISCOLL` make (including `benefits`)?**

In [40]:
JosephDriscoll = sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']
JosephDriscoll['BasePay'].fillna(0) + JosephDriscoll['OvertimePay'].fillna(0) + JosephDriscoll['OtherPay'].fillna(0) + JosephDriscoll['Benefits'].fillna(0)
JosephDriscoll['TotalPay']

24    270324.91
Name: TotalPay, dtype: float64

<br>

**13. What is the `name` of `highest paid` person (NOT including `benefits`)?**

In [48]:
idxMax = (sal['BasePay'].fillna(0).isnull() + + sal['OvertimePay'].fillna(0) + sal['OtherPay'].fillna(0)).idxmax()
sal.iloc[idxMax]['EmployeeName']

'NATHANIEL FORD'

<br>

**14. What is the `name` of `lowest paid` person (including `benefits`)** 
> Do you notice something strange about how much he or she is paid?

In [52]:
idxMin = (sal['BasePay'].fillna(0).isnull() + + sal['OvertimePay'].fillna(0) + sal['OtherPay'].fillna(0) + sal['Benefits'].fillna(0)).idxmin()
display(sal.iloc[idxMin]['EmployeeName'])
display(sal.iloc[idxMin])

'Joe Lopez'

Id                                      148654
EmployeeName                         Joe Lopez
JobTitle            Counselor, Log Cabin Ranch
BasePay                                      0
OvertimePay                                  0
OtherPay                               -618.13
Benefits                                     0
TotalPay                               -618.13
TotalPayBenefits                       -618.13
Year                                      2014
Notes                                      NaN
Agency                           San Francisco
Status                                     NaN
Name: 148653, dtype: object

She has a negative amount

<br>

**15. What was the average aka `mean` `BasePay` of all employees per year? (`2011-2014`)?**
<br>
Each year should have an average `BasePay`. **Hint:** `.groupby()`

In [55]:
print(sal[ (sal['Year'] <= 2014 ) & (sal['Year'] >= 2011 )]['BasePay'].mean())
yearly_averages = sal.groupby('Year')["TotalPayBenefits"].mean()
(yearly_averages[2011] + yearly_averages[2012] + yearly_averages[2013] + yearly_averages[2014]) / 4

66325.44884050643

93497.19292535819

<br>

**16. How many `unique` `job titles` are there?**

In [56]:
sal['JobTitle'].nunique()

2159

<br>

**17. What are the top 5 most common jobs?**

In [57]:
sal['JobTitle'].value_counts().head()

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

<br>

**18. How many `JobTitle`s were held by only a single person, in 2013?**

In [58]:
sal_2013 = sal[sal["Year"] == 2013]
sal_2013["JobTitle"].value_counts()
(sal_2013["JobTitle"].value_counts() == 1).sum()

202

<br>

## Bonus

**<span style="color:red">Hard: </span> How many people have the word `Chief` in their JobTitle?**
**Hint:** [`.str.contains()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.contains.html)

In [59]:
sal["Indexes"] = sal["JobTitle"].str.find("Chief")
len(sal[sal["Indexes"] != -1])

chiefs_sum = 0
for title in sal["JobTitle"]:
    if 'Chief' in title.split(" "):
        chiefs_sum += 1 
print(chiefs_sum)

sal[sal["JobTitle"].str.contains("Chief")].shape[0]

319

423

<br>